from pgmpy.models import BayesianNetwork


# Create a BayesianModel object
model = BayesianNetwork()

# Define the variables
model.add_node("Season")                         # Season (季節)
model.add_node("Weather")                        # Weather (天気)
model.add_node("Comfort")                        # Clothing comfort (服の保護感)
model.add_node("Time_Zone")                      # Time zone (時間帯)
model.add_node("Subjective_Temperature")         # Subjective temperature (主観的な温度)
model.add_node("Indoor_Outdoor")                 # 室内外 (Indoor/Outdoor)
model.add_node("Clothing_Color")                 # 服の色 (Clothing color)
model.add_node("Space_Size")                     # 広さ (Space size)
model.add_node("Experimental_Location")          # 実験場所 (Experimental location)
model.add_node("Influence_by_Third_Party")       # 第三者による影響 (Influence by third party)
model.add_node("Presence_of_Obstacles")          # 遮蔽物の存在 (Presence of obstacles)
model.add_node("Color_Temperature")              # 色温度 (Color temperature)
model.add_node("Subjective_Brightness")          # 主観的明るさ (Subjective brightness)
model.add_node("Satiety_Level")                  # 満腹感 (Satiety level)
model.add_node("Sleepiness")                     # 眠さ (Sleepiness)
model.add_node("Satisfaction_with_Reward")       # 報酬への満足度 (Satisfaction with reward)
model.add_node("Day_of_Week")                    # 曜日 (Day of the week)
model.add_node("Before_After_Meals")             # 食前後 (Before/after meals)
model.add_node("Previous_Night_Sleep_Duration")  # 前日の睡眠時間 (Previous night's sleep duration)
model.add_node("In_Season")                      # 旬 (In season)
model.add_node("Type_of_Clothing")               # 服の種類 (Type of clothing)
model.add_node("Health_Status")                  # 健康状態 (Health status)
model.add_node("Urge_to_Urinate")                # 尿意 (Urge to urinate)
model.add_node("Subjective_Stress_Level")        # 主観的緊迫感 (Subjective stress level)
model.add_node("Medication_Use")                 # 薬の使用 (Medication use)
model.add_node("Degree_of_Thirst")               # 渇の程度 (Degree of thirst)
model.add_node("Long-Term_Stress_Level")         # 長期的な緊迫感 (Long-term stress level)
model.add_node("Supplement_Use")                 # サプリメントの使用 (Supplement use)

# Define the target variable 
model.add_node("Cheating_Indicator")              # 不正の指標 (Cheating indicator)

# Define the dependence 
model.add_edge("Season", "Weather")
model.add_edge("Season", "Type_of_Clothing")
model.add_edge("Season", "Subjective_Temperature")
model.add_edge("Weather", "Subjective_Temperature")
model.add_edge("Type_of_Clothing", "Comfort")
model.add_edge("Time_Zone", "Subjective_Temperature")
model.add_edge("Time_Zone", "Indoor_Outdoor")
model.add_edge("Experimental_Location", "Indoor_Outdoor")
model.add_edge("Experimental_Location", "Influence_by_Third_Party")
model.add_edge("Indoor_Outdoor", "Influence_by_Third_Party")
model.add_edge("Indoor_Outdoor", "Space_Size")
model.add_edge("Experimental_Location", "Subjective_Brightness")
model.add_edge("Color_Temperature", "Subjective_Brightness")
model.add_edge("Subjective_Brightness", "Sleepiness")
model.add_edge("Satiety_Level", "Sleepiness")
model.add_edge("Before_After_Meals", "Satiety_Level")
model.add_edge("Subjective_Brightness", "Sleepiness")
model.add_edge("Previous_Night_Sleep_Duration", "Sleepiness")
model.add_edge("Satiety_Level", "Subjective_Stress_Level")
model.add_edge("Urge_to_Urinate", "Subjective_Stress_Level")
model.add_edge("Degree_of_Thirst", "Subjective_Stress_Level")
model.add_edge("Long-Term_Stress_Level", "Subjective_Stress_Level")
model.add_edge("Supplement_Use", "Long-Term_Stress_Level")
model.add_edge("Medication_Use", "Long-Term_Stress_Level")
model.add_edge("Health_Status", "Long-Term_Stress_Level")

model.add_edge("Comfort", "Cheating_Indicator")
model.add_edge("Clothing_Color", "Cheating_Indicator")
model.add_edge("Space_Size", "Cheating_Indicator")
model.add_edge("Presence_of_Obstacles", "Cheating_Indicator")
model.add_edge("Sleepiness", "Cheating_Indicator")
model.add_edge("Satisfaction_with_Reward", "Cheating_Indicator")
model.add_edge("Subjective_Stress_Level", "Cheating_Indicator")
model.add_edge("Day_of_Week", "Cheating_Indicator")
model.add_edge("In_Season", "Cheating_Indicator")
model.add_edge("Influence_by_Third_Party", "Cheating_Indicator")

model.add_edge("Subjective_Temperature", "Cheating_Indicator")

