nodes = ['Season', 'Weather', 'Comfort', 'Time_Zone', 'Subjective_Temperature', 'Indoor_Outdoor', 'Clothing_Color', 'Space_Size', 'Experimental_Location', 'Influence_by_Third_Party', 'Presence_of_Obstacles', 'Color_Temperature', 'Subjective_Brightness', 'Satiety_Level', 'Sleepiness', 'Satisfaction_with_Reward', 'Day_of_Week', 'Before_After_Meals', 'Previous_Night_Sleep_Duration', 'In_Season', 'Type_of_Clothing', 'Health_Status', 'Urge_to_Urinate', 'Subjective_Stress_Level', 'Medication_Use', 'Degree_of_Thirst', 'Long-Term_Stress_Level', 'Supplement_Use', 'Cheating_Indicator', 'Term_Stress_Level']


# node_states = {
#     'Season': 2, 
#     'Weather': 4, 
#     'Comfort': 7, 
#     'Time_Zone': 3, 
#     'Subjective_Temperature': 7, 
#     'Indoor_Outdoor': 2, 
#     'Clothing_Color': 7, 
#     'Space_Size': 7, 
#     'Experimental_Location': 7, 
#     'Influence_by_Third_Party': 7, 
#     'Presence_of_Obstacles': 2, 
#     'Color_Temperature': 3, 
#     'Subjective_Brightness': 7, 
#     'Satiety_Level': 7, 
#     'Sleepiness': 7, 
#     'Satisfaction_with_Reward': 7, 
#     'Day_of_Week': 5, 
#     'Before_After_Meals': 5, 
#     'Previous_Night_Sleep_Duration': 4, 
#     'In_Season': 3, 
#     'Type_of_Clothing': 2, 
#     'Health_Status': 3, 
#     'Urge_to_Urinate': 7, 
#     'Subjective_Stress_Level': 7, 
#     'Medication_Use': 2, 
#     'Degree_of_Thirst': 7, 
#     'Long-Term_Stress_Level': 7, 
#     'Supplement_Use': 2,
#     'Cheating_Indicator': 10
#     }

node_states = {
    'Season': 2, 
    'Weather': 2, 
    'Comfort': 2, 
    'Time_Zone': 2, 
    'Subjective_Temperature': 2, 
    'Indoor_Outdoor': 2, 
    'Clothing_Color': 2, 
    'Space_Size': 2, 
    'Experimental_Location': 2, 
    'Influence_by_Third_Party': 2, 
    'Presence_of_Obstacles': 2, 
    'Color_Temperature': 2, 
    'Subjective_Brightness': 2, 
    'Satiety_Level': 2, 
    'Sleepiness': 2, 
    'Satisfaction_with_Reward': 2, 
    'Day_of_Week': 2, 
    'Before_After_Meals': 2, 
    'Previous_Night_Sleep_Duration': 2, 
    'In_Season': 2, 
    'Type_of_Clothing': 2, 
    'Health_Status': 2, 
    'Urge_to_Urinate': 2, 
    'Subjective_Stress_Level': 2, 
    'Medication_Use': 2, 
    'Degree_of_Thirst': 2, 
    'Long-Term_Stress_Level': 2, 
    'Supplement_Use': 2,
    'Cheating_Indicator': 5
    }